version: '3.4'
services:
  app:
    image: koltinapi
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: bitnami/mongodb
    container_name: database
    ports:
      - 27017:27017

  