version: '3.4'
services:
  app:
    image: koltin-api
    container_name: app
    ports:
      - 8080:80
    depends_on:
      - database
  database:
    image: bitnami/mongodb
    container_name: database
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGODB_USER="root" 
      - MONGODB_PASS="root"
    ports:
      - 27016:27017

  